### ISSUE TITLE
The Cron Job

### ISSUE THREAD

**Issue by Vendo232** [hpeyerl/airthingswave-mqtt#7]
Hello

your guide is great and only one which I managed to integrate and use with HA.

Struggle a little with the Cron job setup.

would this be the way to do it? In this picture the Cron should update every 5 min.

the command after python ... works by it self and it pushed data to HA.

Also I plan to change */5 yo */60 once I figure out how Cron works

![image](https://user-images.githubusercontent.com/44098230/93795868-4157fa00-fbf7-11ea-9c80-9e529d45868e.png)

getting this error "(CRON) info (No MTA installed, discarding output)"

**Comment by hpeyerl** [comment]
MTA means "Mail Transport Agent".  Meaning you haven't installed a mail server like Postfix or similar.  So it's just cron saying it can't send you mail.

I think you have one too many '*'s there.

**Comment by hpeyerl** [comment]
Also, "*/60" is the same as 1-hour.  So if you want it to run every hour, you would do:

0 * * * * python -m ......

and it'll run at the 0th minute every hour.

you have the correct number of '*'s.

**Comment by Vendo232** [comment]
it worked, it worked it worked.
had to install Postfix and add MAILTO="" into crontab then it worked. 
I have HA showing me the RADON levels!

Thank you, great work!

![C55546465apture](https://user-images.githubusercontent.com/44098230/93826871-5e0b2680-fc25-11ea-9c32-dba1cbc355ea.JPG)
