### ISSUE TITLE
Not compatible with Wave 2nd Gen [Data structure have changed]

### ISSUE THREAD

**Issue by hirofairlane** [hpeyerl/airthingswave-mqtt#9]
I have two Airthings wave, one is 1st Gen and newer one is 2nd Gen (it does display battery status in Airthings app).

The reason seems to be that data structure is not compatible between both versions. There is even two versions of read_wave.py in official Airthings github https://github.com/Airthings/wave-reader

It would be great if you consider to make a compatible version of your mqtt tool. It works great with my 1st gen wave

**Comment by hpeyerl** [comment]
If someone sends me a 2nd Gen unit, I'd be happy to update the code.
